In [1]:
import numpy as np

In [3]:
arr = np.arange (0,30,3) #define um array de 0 a 30 com passo 3

In [4]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
arr[4] #retorna o numero contido no indice 4 do array

12

In [6]:
arr[2:6] #terorna os numeros contidos nos indices de 2 a 5 (o 6 não é mostrado)

array([ 6,  9, 12, 15])

In [7]:
arr[:5] #retorna os elementos a partir do inicio até o indice 4 (5 não é incluso)

array([ 0,  3,  6,  9, 12])

In [8]:
arr[5:] #o indice 5 ao final

array([15, 18, 21, 24, 27])

In [10]:
arr[3:] = 100 #todos os elementos a partir do indice 3 valerão 100

In [11]:
arr

array([  0,   3,   6, 100, 100, 100, 100, 100, 100, 100])

In [13]:
arr = np.arange(50).reshape((5,10)) #cria um array e logo em seguida o transforma em matriz

In [14]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [15]:
arr.shape # tamanho da matriz

(5, 10)

In [21]:
arr[:3][:]#retorna as linhas

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [25]:
arr2 = arr[:3]

In [27]:
arr2 #arr2 é um ponteiro para arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
arr2 = arr[:3].copy() #agora sim o arr2 é um arry com valores proprios

In [37]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
arr2[:] = 100

In [40]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [42]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [66]:
arr[0:5,3] #slice de matriz ["linha", "coluna"]

array([ 3, 13, 23, 33, 43])

In [69]:
arr[1:2,5]

array([15])

In [60]:
arr>40

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [62]:
bol = arr>40

In [64]:
arr[bol]

array([41, 42, 43, 44, 45, 46, 47, 48, 49])