In [2]:
import numpy as np

In [6]:
minha_lista = [1,2,3]

In [7]:
minha_lista

[1, 2, 3]

In [10]:
np.array(minha_lista)

array([1, 2, 3])

In [13]:
minha_matriz = [[1,2,3],[2,4,5],[2,5,8]]

In [15]:
np.array(minha_matriz)

array([[1, 2, 3],
       [2, 4, 5],
       [2, 5, 8]])

In [20]:
np.arange(0,19,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.zeros(4)

array([0., 0., 0., 0.])

In [24]:
arr = np.zeros(4)

In [26]:
arr

array([0., 0., 0., 0.])

In [28]:
arr = np.zeros((6,6))

In [29]:
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
arr = np.ones((4,4))

In [33]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [45]:
np.random.rand(4)

array([0.01139156, 0.98275216, 0.54908607, 0.1299038 ])

In [48]:
np.random.rand(5,3,4)

array([[[0.51475623, 0.03152831, 0.81613924, 0.59752775],
        [0.31938411, 0.01240998, 0.3168902 , 0.71156706],
        [0.75117363, 0.29133303, 0.81506148, 0.60561843]],

       [[0.89168939, 0.11256853, 0.33290524, 0.73489791],
        [0.44991906, 0.82435544, 0.90365186, 0.73220428],
        [0.42826904, 0.00228714, 0.77122362, 0.44814746]],

       [[0.08620297, 0.48755894, 0.55128746, 0.59120192],
        [0.56992257, 0.02420702, 0.94469942, 0.54389636],
        [0.76931026, 0.92291828, 0.48154514, 0.42066027]],

       [[0.69121294, 0.78778139, 0.0831269 , 0.51726167],
        [0.42927538, 0.91629031, 0.47550539, 0.47364173],
        [0.73144509, 0.62767688, 0.05782605, 0.75282071]],

       [[0.52846161, 0.04321895, 0.84768697, 0.11538519],
        [0.63584172, 0.2574172 , 0.05506211, 0.77301085],
        [0.59775384, 0.22374183, 0.64653777, 0.18472564]]])

In [50]:
np.random.randn(3)

array([-0.34314024,  0.82560146,  0.9588183 ])

In [51]:
np.random.randint(1,39,4)

array([ 5, 34,  7, 12])

In [57]:
arr = np.random.rand(25)

In [58]:
arr

array([0.17211616, 0.76032507, 0.28763267, 0.4503396 , 0.79981232,
       0.70255959, 0.8139112 , 0.90363494, 0.04881377, 0.66556984,
       0.23291336, 0.62055815, 0.21011236, 0.60623096, 0.48268692,
       0.2448257 , 0.437984  , 0.95453356, 0.96622139, 0.69414945,
       0.99092623, 0.55026445, 0.90316565, 0.91406119, 0.71905355])

In [61]:
arr.reshape((5,5))

array([[0.17211616, 0.76032507, 0.28763267, 0.4503396 , 0.79981232],
       [0.70255959, 0.8139112 , 0.90363494, 0.04881377, 0.66556984],
       [0.23291336, 0.62055815, 0.21011236, 0.60623096, 0.48268692],
       [0.2448257 , 0.437984  , 0.95453356, 0.96622139, 0.69414945],
       [0.99092623, 0.55026445, 0.90316565, 0.91406119, 0.71905355]])

In [62]:
arr.shape

(25,)

In [64]:
arr.max()

0.9909262321381387

In [65]:
arr.min()

0.04881376594093334

In [67]:
arr.argmax()

20

In [68]:
arr.argmin()

8